### ISSUE TITLE
Generate Minefield before first uncover

### ISSUE THREAD

**Issue by Flash0ver** [Flash0ver/F0.Minesweeper#10]
The first uncover may already uncover a mine.

**Comment by thomas-pemsel** [comment]
Do we want this to be an option that can be set, or is this issue being replaces/made obsolete with issue #11?

**Comment by manuelzelenka** [comment]
> Do we want this to be an option that can be set, or is this issue being replaces/made obsolete with issue #11?

tbh I can't really remember anymore. From my personal view I'd prefer to have it as an option and the user can choose which option he/she takes

**Comment by Flash0ver** [comment]
Eventually, we planned to have both #10 and #11. I don't mind with which we start. And we could make it an _option_ right away, or make it an option later on when we implement the alternative.
