### ISSUE TITLE
Show end state of game

### ISSUE THREAD

**Issue by Flash0ver** [Flash0ver/F0.Minesweeper#28]
* all non-mined cells are uncovered
* a mined cell is uncovered

**Comment by dev-in-disguise** [comment]
I'll try to implement it similary to the original minesweeper game. This means:

* all non-mined cells are uncovered
every mine is marked as flagged
* a mined cell is uncovered
all mines are uncovered and the clicked mine has a red background color

**Comment by dev-in-disguise** [comment]
Closed by #67
